### PR TITLE
Add indicator views to the camera feed to demonstrate how to transform results fro...

### PR DESCRIPTION
**Pull request by jackwu95**
...m both metadata and features for face detection.

### CODE REVIEW

**Comment by MattFoley** [comment]
Hey, thanks for this! 

I will take a look at this in detail later tonight. 

I think my only request right now is to move the main chunk of the code you added to methods. ie: all the new code you've added to the viewDidLoad, and all the code you've added to the detection block, just make those two new methods.

**Comment by jackwu95** [comment]
Sounds good, I'll clean it up! I'll also add buttons to show/hide the boxes like the 'Stachecam app.

**Comment by jackwu95** [comment]
Alright, feel free to let me know if you have any more suggestions. 
Really love what you've done with this library btw!

**Comment by MattFoley** [comment]
Thanks! and thanks for this, just finally had a chance to review it, works excellently!

**Pull request merged**
